name: Ensure visibility

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: {}

jobs:
  ensure_visibility:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update visibility
        id: ensure_visibility
        run: python3 ensure_visibility.py "${{ secrets.ACCESS_TOKEN }}"

      - name: Generate README.md
        if: ${{ steps.ensure_visibility.outputs.updated == '1' }}
        run: python3 generate.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.ensure_visibility.outputs.updated == '1' }}
        with:
          default_author: github_actions
          add: |
            - metadata.json
            - README.md
          message: 'metadata: bump semester'
